// Generated by ~/Projects/design (`design kotlin --hue 250`). Do not edit: change tokens.json and regenerate.
package com.kivan.tether.ui.theme

import androidx.compose.ui.graphics.Color

/** Every colour in the design language. Dark only; there is no light scheme. */
object Palette {
    val Bg = Color(0xFF0F1114)
    val SurfaceLowest = Color(0xFF0B0D10)
    val SurfaceLow = Color(0xFF13161A)
    val Surface = Color(0xFF171A1F)
    val SurfaceHigh = Color(0xFF20242A)
    val SurfaceHighest = Color(0xFF2A2F36)
    val Line = Color(0xFF2A2F36)
    val Outline = Color(0xFF3A4049)
    val Text = Color(0xFFECEEF1)
    val Muted = Color(0xFF98A0AA)
    val Danger = Color(0xFFFF6B5E)
    val OnDanger = Color(0xFF2A0705)
    val DangerDim = Color(0xFF4A1814)
    val Success = Color(0xFF5CC8E8)
    val Warning = Color(0xFFF2B84B)
    val Accent = Color(0xFF95C9FF)
    val OnAccent = Color(0xFF071727)
    val AccentDim = Color(0xFF193550)
    val Tile = Color(0xFF0E3F6A)
}
