// Generated by ~/Projects/design (`design kotlin --hue 250`). Do not edit: change tokens.json and regenerate.
package com.kivan.tether.ui.theme

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.FiniteAnimationSpec
import androidx.compose.animation.core.tween

/** One calm ease-out for everything. */
object Motion {
    const val DURATION_MS = 180
    val Easing = CubicBezierEasing(0.2f, 0.8f, 0.2f, 1f)
    /** The hero number scales to this and back when its value changes. */
    const val PULSE_SCALE = 1.04f

    fun <T> calm(): FiniteAnimationSpec<T> = tween(DURATION_MS, easing = Easing)
}
