// Generated by ~/Projects/design (`design kotlin --hue 250`). Do not edit: change tokens.json and regenerate.
package com.kivan.tether.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.Composable

/** Fixed palette mapped onto Material 3 roles. No dynamic colour, no light theme. */
val AppColorScheme = darkColorScheme(
    primary = Palette.Accent,
    onPrimary = Palette.OnAccent,
    primaryContainer = Palette.AccentDim,
    onPrimaryContainer = Palette.Accent,
    inversePrimary = Palette.AccentDim,
    secondary = Palette.Accent,
    onSecondary = Palette.OnAccent,
    secondaryContainer = Palette.AccentDim,
    onSecondaryContainer = Palette.Accent,
    tertiary = Palette.Success,
    onTertiary = Palette.Bg,
    tertiaryContainer = Palette.SurfaceHigh,
    onTertiaryContainer = Palette.Success,
    background = Palette.Bg,
    onBackground = Palette.Text,
    surface = Palette.Bg,
    onSurface = Palette.Text,
    surfaceVariant = Palette.SurfaceHigh,
    onSurfaceVariant = Palette.Muted,
    surfaceTint = Palette.Bg,
    inverseSurface = Palette.Text,
    inverseOnSurface = Palette.Bg,
    error = Palette.Danger,
    onError = Palette.OnDanger,
    errorContainer = Palette.DangerDim,
    onErrorContainer = Palette.Danger,
    outline = Palette.Outline,
    outlineVariant = Palette.Line,
    scrim = Palette.SurfaceLowest,
    surfaceBright = Palette.SurfaceHighest,
    surfaceDim = Palette.Bg,
    surfaceContainerLowest = Palette.SurfaceLowest,
    surfaceContainerLow = Palette.SurfaceLow,
    surfaceContainer = Palette.Surface,
    surfaceContainerHigh = Palette.SurfaceHigh,
    surfaceContainerHighest = Palette.SurfaceHighest,
)

@Composable
fun AppTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = AppColorScheme,
        typography = AppTypography,
        shapes = AppShapes,
        content = content,
    )
}
