// Generated by ~/Projects/design (`design kotlin --hue 250`). Do not edit: change tokens.json and regenerate.
package com.kivan.tether.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontVariation
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import com.kivan.tether.R

private fun variable(res: Int, vararg weights: Int) = FontFamily(
    weights.map { w -> Font(res, FontWeight(w), variationSettings = FontVariation.Settings(FontVariation.weight(w))) }
)

/** Rubik (variable, Hebrew built in): all text. */
val Rubik = variable(R.font.rubik, 300, 400, 500, 600, 700)

/** Geist Mono (variable, no Hebrew): ids, times, code. */
val GeistMono = variable(R.font.geist_mono, 400, 500, 600)

/** The design language's own styles; `AppTypography` maps them onto Material roles. */
object AppType {
    val hero = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 76.sp,
        lineHeight = 76.sp,
        letterSpacing = -0.02.em,
        fontFeatureSettings = "tnum",
    )
    val heroSmall = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 48.sp,
        lineHeight = 52.sp,
        letterSpacing = -0.02.em,
        fontFeatureSettings = "tnum",
    )
    /** Set the text in capitals: `text.uppercase()` (or use [Eyebrow]). */
    val eyebrow = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W500,
        fontSize = 11.sp,
        lineHeight = 14.sp,
        letterSpacing = 0.12.em,
    )
    val title = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 22.sp,
        lineHeight = 28.sp,
        letterSpacing = -0.01.em,
    )
    val heading = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 17.sp,
        lineHeight = 22.sp,
        letterSpacing = 0.em,
    )
    val body = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W400,
        fontSize = 15.sp,
        lineHeight = 22.sp,
        letterSpacing = 0.em,
    )
    val label = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W500,
        fontSize = 14.sp,
        lineHeight = 18.sp,
        letterSpacing = 0.em,
    )
    val small = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W400,
        fontSize = 12.5.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.em,
    )
    val mono = TextStyle(
        fontFamily = GeistMono,
        fontWeight = FontWeight.W400,
        fontSize = 12.5.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.em,
        fontFeatureSettings = "tnum",
    )
}

val AppTypography = Typography(
    displayLarge = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 76.sp,
        lineHeight = 76.sp,
        letterSpacing = -0.02.em,
        fontFeatureSettings = "tnum",
    ),
    displayMedium = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 48.sp,
        lineHeight = 52.sp,
        letterSpacing = -0.02.em,
        fontFeatureSettings = "tnum",
    ),
    displaySmall = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 36.sp,
        lineHeight = 39.sp,
        letterSpacing = -0.02.em,
        fontFeatureSettings = "tnum",
    ),
    headlineLarge = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 30.sp,
        lineHeight = 38.182.sp,
        letterSpacing = -0.01.em,
    ),
    headlineMedium = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 26.sp,
        lineHeight = 33.091.sp,
        letterSpacing = -0.01.em,
    ),
    headlineSmall = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 24.sp,
        lineHeight = 30.545.sp,
        letterSpacing = -0.01.em,
    ),
    titleLarge = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 22.sp,
        lineHeight = 28.sp,
        letterSpacing = -0.01.em,
    ),
    titleMedium = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 17.sp,
        lineHeight = 22.sp,
        letterSpacing = 0.em,
    ),
    titleSmall = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W600,
        fontSize = 14.sp,
        lineHeight = 18.sp,
        letterSpacing = 0.em,
    ),
    bodyLarge = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W400,
        fontSize = 15.sp,
        lineHeight = 22.sp,
        letterSpacing = 0.em,
    ),
    bodyMedium = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W400,
        fontSize = 14.sp,
        lineHeight = 20.533.sp,
        letterSpacing = 0.em,
    ),
    bodySmall = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W400,
        fontSize = 12.5.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.em,
    ),
    labelLarge = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W500,
        fontSize = 14.sp,
        lineHeight = 18.sp,
        letterSpacing = 0.em,
    ),
    labelMedium = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W500,
        fontSize = 12.5.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.em,
    ),
    labelSmall = TextStyle(
        fontFamily = Rubik,
        fontWeight = FontWeight.W500,
        fontSize = 11.sp,
        lineHeight = 14.sp,
        letterSpacing = 0.12.em,
    ),
)
