// Generated by ~/Projects/design (`design kotlin --hue 150`). Do not edit: change tokens.json and regenerate.
package com.kivan.tether.dibs.ui.theme

import androidx.compose.animation.core.Animatable
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.unit.dp

/** Small tracked capitals; optional accent dot marks the live/active thing. */
@Composable
fun Eyebrow(text: String, modifier: Modifier = Modifier, dot: Boolean = false, color: Color = Palette.Muted) {
    Row(modifier, verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(Space.S)) {
        if (dot) Box(Modifier.size(7.dp).background(Palette.Accent, Pill))
        Text(text.uppercase(), style = AppType.eyebrow, color = color)
    }
}

/** The signature: one big tabular number that pulses when it changes. */
@Composable
fun HeroNumber(value: String, modifier: Modifier = Modifier, style: TextStyle = AppType.hero, color: Color = Palette.Text) {
    val scale = remember { Animatable(1f) }
    val started = remember { BooleanArray(1) }
    LaunchedEffect(value) {
        if (!started[0]) { started[0] = true; return@LaunchedEffect }
        scale.animateTo(Motion.PULSE_SCALE, Motion.calm())
        scale.animateTo(1f, Motion.calm())
    }
    Text(value, modifier.graphicsLayer { scaleX = scale.value; scaleY = scale.value }, style = style, color = color)
}

/** Eyebrow + hero number on the large-radius surface panel. */
@Composable
fun HeroPanel(label: String, value: String, modifier: Modifier = Modifier, dot: Boolean = false, below: @Composable () -> Unit = {}) {
    Column(
        modifier.fillMaxWidth().background(Palette.Surface, AppShapes.large).padding(horizontal = Space.L, vertical = Space.L),
        verticalArrangement = Arrangement.spacedBy(Space.XS),
    ) {
        Eyebrow(label, dot = dot)
        HeroNumber(value)
        below()
    }
}
