// Generated by ~/Projects/design (`design kotlin --hue 150`). Do not edit: change tokens.json and regenerate.
package com.kivan.tether.dibs.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Shapes
import androidx.compose.ui.unit.dp

/** small 8 (fields), medium 14 (buttons, rows, cards), large 24 (hero panel, sheets). Chips are [Pill]. */
val AppShapes = Shapes(
    extraSmall = RoundedCornerShape(8.dp),
    small = RoundedCornerShape(8.dp),
    medium = RoundedCornerShape(14.dp),
    large = RoundedCornerShape(24.dp),
    extraLarge = RoundedCornerShape(24.dp),
)

val Pill = RoundedCornerShape(percent = 50)

/** 4-point spacing. Screen gutter is `Space.L`; separate groups with space, not dividers. */
object Space {
    val XS = 4.dp
    val S = 8.dp
    val M = 12.dp
    val L = 16.dp
    val XL = 24.dp
    val XXL = 32.dp
}
